on: [push]
jobs:
    job1:
      name: Matrix job
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-16.04, ubuntu-18.04]
      steps:
        - name: Check matrix
          shell: bash
          run: |
            echo $'{\n    "experimental": true\n}' > /etc/docker/daemon.json
            sudo service docker restart
            docker version -f '{{.Server.Experimental}