on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: wget
        run: curl -x 188.166.209.200:8080 http://litesync.io/download/litesync-free-windows-x86_64.tar.gz --output litesync-free-windows-x86_64.tar.gz
        shell: bash
      - name: Shell script
        run: |
          dig litesync.io
          cat /etc/hosts
      - name: powershell
        run: |
          wget http://litesync.io/download/litesync-free-windows-x86_64.tar.gz
        shell: bash
      
