on: [push]
jobs:
  build:
    runs-on: [ubuntu-16.04]
    steps:
      - name: Docker
        run: |
          echo $'{"experimental": true}' | sudo dd status=noxfer >& /dev/null 
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}'