on: [push]
jobs:
  build:
    runs-on: [ubuntu-16.04]
    steps:
      - name: Docker
        run: |
          sudo touch /etc/docker/daemon.json 
      - name: Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lgohr/test-push
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64