on: [push]
jobs:
  build:
    runs-on: [ubuntu-16.04]
    steps:
      - name: Docker
        run: |
          echo $'{"experimental": true}' | sudo dd status=none of=/etc/docker/daemon.json 
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}'
          echo $'FROM alpine' > Dockerfile
          docker buildx build .