on: [push]
jobs:
  build:
    runs-on: [ubuntu-16.04]
    steps:
      - name: Plain job
        run: |
          echo $'{"experimental": true}' | sudo dd status=none of=/etc/docker/daemon.json 
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}' 
      - id: in-with
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lgohr/test-push
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      
