on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Plain job
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install drawio
        shell: bash
      
