on: [push]
jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Plain job
        run: Invoke-WebRequest http://litesync.io/download/litesync-free-windows-x86_64.tar.gz -OutFile litesync-free-windows-x86_64.tar.gz
        shell: powershell 
      
