on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Plain job
        run: |
          wget -O /tmp/sbt.tgz "https://github.com/sbt/sbt/releases/download/v1.4.9/sbt-1.4.9.tgz"
          sudo tar zxf /tmp/sbt.tgz -C /usr/share
          sudo rm -rf /usr/bin/sbt
          sudo ln -s /usr/share/sbt/bin/sbt /usr/bin/sbt
          sbt sbtVersion
        shell: bash
      
