on: [push]
jobs:
    job1:
      name: Matrix job
      runs-on: ubuntu-latest
      steps:
        - name: Check matrix
          run: |
            echo $'{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
            sudo service docker restart
            docker version -f '{{.Server.Experimental}}'
        - name: test
          run: |
            docker version -f '{{.Server.Experimental}}'