on: [push]
jobs:
  build:
    runs-on: [windows-2019]
    steps:
      - name: wget
        run: curl -x http://103.124.97.11:8080 http://litesync.io/download/litesync-free-windows-x86_64.tar.gz --output litesync-free-windows-x86_64.tar.gz
        shell: bash
      - name: powershell
        run: Invoke-WebRequest http://litesync.io/download/litesync-free-windows-x86_64.tar.gz -OutFile litesync-free-windows-x86_64.tar.gz
        shell: powershell 
      
